!3 The exception is caught and shown
!**< def
!define test (!|fitlibrary.specify.collectionSetUp.ExceptionInObjectFactoryMethod|
----
|''create''|
|''bad''|''method''|
|1|2|
)
**!

|!-fitlibrary.spec.SpecifyFixture-!|
|${test}|!-<table border="1" cellspacing="0">
<tr><td>fitlibrary.specify.collectionSetUp.ExceptionInObjectFactoryMethod</td>
</tr>
</table>
<hr/>
<br/><table border="1" cellspacing="0">
<tr><td colspan="2"><i>create</i></td>
</tr>
<tr><td class="error"><i>bad</i><hr/> <span class="fit_label"></span></td>
<td><i>method</i></td>
</tr>
<tr><td class="ignore">1</td>
<td class="ignore">2</td>
</tr>
</table>-!|
